version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: stock_user
      POSTGRES_DB: stock_database

    ports:
      - "5432:5432"